export const NOTICE_LIST_REQUEST = 'NOTICE_LIST_REQUEST';
export const NOTICE_LIST_SUCCESS = 'NOTICE_LIST_SUCCESS';
export const NOTICE_LIST_FAILED = 'NOTICE_LIST_FAILED';

export const NOTICE_CREATE_REQUEST = 'NOTICE_CREATE_REQUEST';
export const NOTICE_CREATE_SUCCESS = 'NOTICE_CREATE_SUCCESS';
export const NOTICE_CREATE_FAILED = 'NOTICE_CREATE_FAILED';
export const NOTICE_CREATE_RESET = 'NOTICE_CREATE_RESET';