export const ADDVERTISE_LIST_REQUEST = 'ADDVERTISE_LIST_REQUEST';
export const ADDVERTISE_LIST_SUCCESS = 'ADDVERTISE_LIST_SUCCESS';
export const ADDVERTISE_LIST_FAILED = 'ADDVERTISE_LIST_FAILED';

export const ADDVERTISE_CREATE_REQUEST = 'ADDVERTISE_CREATE_REQUEST';
export const ADDVERTISE_CREATE_SUCCESS = 'ADDVERTISE_CREATE_SUCCESS';
export const ADDVERTISE_CREATE_FAILED = 'ADDVERTISE_CREATE_FAILED';
export const ADDVERTISE_CREATE_RESET = 'ADDVERTISE_CREATE_RESET';