export const EMPLOYMENT_LIST_REQUEST = 'EMPLOYMENT_LIST_REQUEST';
export const EMPLOYMENT_LIST_SUCCESS = 'EMPLOYMENT_LIST_SUCCESS';
export const EMPLOYMENT_LIST_FAILED = 'EMPLOYMENT_LIST_FAILED';

export const EMPLOYMENT_CREATE_REQUEST = 'EMPLOYMENT_CREATE_REQUEST';
export const EMPLOYMENT_CREATE_SUCCESS = 'EMPLOYMENT_CREATE_SUCCESS';
export const EMPLOYMENT_CREATE_FAILED = 'EMPLOYMENT_CREATE_FAILED';
export const EMPLOYMENT_CREATE_RESET = 'EMPLOYMENT_CREATE_RESET';